---
- name: Ensure the {{ nginx_package }} package is installed
  ansible.builtin.package:
    name: "{{ nginx_package }}"
    state: present

- name: Start the {{ nginx_service }} service if needed
  ansible.builtin.service:
    name: "{{ nginx_service }}"
    state: started
    enabled: true

- name: Deploy custom index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: "0644"
  notify:
    - restart nginx